import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { Toaster } from "sonner";
import { Suspense } from "react";
import Loader from "@/components/Loader/Loader";
import { Providers } from "./providers";
import { AosProvider } from "@/components/AosProvider/AosProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Toyour Teacher",
  description: "Generated by Waheedul Islam",
  verification: {
    google: "DB8mA8kH-zSGT0FHg85ez1OLt1YUUWLhBPpTyUESZWg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-white to-blue-50`}
        >
          <AosProvider>
            <Navbar />
            <Toaster richColors position="top-center" />
            <Suspense fallback={<Loader />}>{children}</Suspense>
            <Footer />
          </AosProvider>
        </body>
      </html>
    </Providers>
  );
}
